dist: xenial

language: python
python:
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7"
  - "3.7-dev"
# command to install dependencies
before_install:
  - pip install poetry
install:
- poetry install

env:
  - TEST=TEST

# command to run tests
script:
  - poetry run pytest

after_success:
  - poetry run coveralls

sudo: false # route your build to the container-based infrastructure for a faster build

notifications:
  email: false
