language: python
python:
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
# command to install dependencies
install:
  - python -m pip install -r requirements_test.txt
# command to run tests
script:
  - TEST=TRUE; python runTests.py

sudo: false # route your build to the container-based infrastructure for a faster build

notifications:
  email: false
